ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
        exclude: 'asv_bench/asv.conf.json'
      - id: check-yaml
      - id: debug-statements
      - id: mixed-line-ending

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.0
    hooks:
      - id: pyupgrade
        args:
          - '--py38-plus'

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
      - id: black-jupyter

  - repo: https://github.com/keewis/blackdoc
    rev: v0.3.7
    hooks:
      - id: blackdoc
      
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.237'
    hooks:
      - id: ruff
        args: ['--fix']

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
